FROM openjdk:11.0.16-jre
MAINTAINER Buon SUI <boonsuli@gmail.com>
VOLUME /app
RUN mkdir -p /app/
WORKDIR /app
COPY ./target/trailerplan-idserver-1.0.0-SNAPSHOT.jar /app/trailerplan-idserver.jar
CMD ["/usr/local/openjdk-11/bin/java", "-Dspring.profiles.active=dev-local-bd-memory-hsql", "-jar", "/app/trailerplan-idserver.jar"]
